name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Cache Buildozer JSONs
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ steps.get-date.outputs.date }}
      - name: Build with Buildozer
        uses: ArtemGovorov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AI-Travel-App
          path: ${{ steps.buildozer.outputs.filename }}
